### PR TITLE
Keep window on all spaces option

### PR DESCRIPTION
**Pull request by Fordi**
Implements: https://github.com/yuhua-chen/LayerX/issues/11

This PR adds a menu item that, when enabled, will keep the overlay window where it is when the user switches spaces.

### CODE REVIEW

**Comment by yuhua-chen** [comment]
Thank you so much. I'm gonna merge these PRs and give you credit on README. :)

**Comment by yuhua-chen** [comment]
Oh no. This PR has been conflicted with previous ones. 😭

**Comment by Fordi** [comment]
Figured that'd happen. Merged.

**Comment by Fordi** [comment]
Also, fixed my spacing inconsistencies from the last PRs.

**Comment by yuhua-chen** [comment]
Awesome! Thank you. 👍

**Pull request merged**
